# Makefile
# Author: Simon Kaemmer

# Variablen
CC = gcc -g
CFLAGS = -W -Wall -Wpedantic
RM = rm -f

TARGET1 = aufgabe1
TARGET2 = aufgabe2
TARGET3 = aufgabe3
TARGET4 = aufgabe4
TARGET5 = aufgabe5
TARGET6 = aufgabe6
TARGET7 = aufgabe7
TARGET8 = aufgabe8

.PHONY: all clean

all: $(TARGET1) $(TARGET2) $(TARGET3) $(TARGET4) $(TARGET5) $(TARGET6) $(TARGET7) $(TARGET8)

clean: $(RM) $(TARGET1) $(TARGET2) $(TARGET3) $(TARGET4) $(TARGET5) $(TARGET6) $(TARGET7) $(TARGET8)

