# Makefile
# Author: Simon Kaemmer

# Variablen
CC = gcc -g
CFLAGS = -W -Wall -Wpedantic
RM = rm -f

TARGET1 = null
TARGET2 = nofree
TARGET3 = zeroat100
TARGET4 = printafterfree
TARGET5 = aufgabe7
TARGET6 = vector

.PHONY: all clean

all: $(TARGET1) $(TARGET2) $(TARGET3) $(TARGET4) $(TARGET5) $(TARGET6)

clean: $(RM) $(TARGET1)