# Makefile
# Author: Simon Kaemmer

# Variablen
CC = gcc -g
CFLAGS = -W -Wall -Wpedantic
RM = rm -f

TARGET1 = mes_syscall
TARGET2 = mes_cs

.PHONY: all clean

all: $(TARGET1) $(TARGET2)

clean: $(RM) $(TARGET1) $(TARGET2)

